### ISSUE TITLE
README.md Google Play link broken

### ISSUE THREAD

**Issue by Thynix** [louboco/Icicle#1]
Icicle is no longer on Google Play. The [Google Play link](https://github.com/louboco/Icicle/blob/208ce944d1ab8e9138c87e451c0b2e8df7e56240/README.md#links) goes to a page which reads "We're sorry, the requested URL was not found on this server."

I see that it's on [F-Droid](https://f-droid.org/repository/browse/?fdid=co.loubo.icicle), but I don't have that app store installed. Would it be reasonable to have the app both on F-Droid and Google Play?

**Comment by louboco** [comment]
Updated the README to remove links.

Another of my apps was removed from the Play store with no explanation why, and all my appeals went unanswered. Due to this I have no desire to deal with the Play store. To be honest, I have no desire to continue working on Android apps for that matter.

The apk can be downloaded from Freenet and installed directly.
